[project]
name = "01-hello-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.12.1",
    "openai-agents>=0.3.3",
    "pillow>=11.3.0",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]
